version: '3.9'

services:
  esp-idf:
    build: .
    volumes:
      - ./ESP32:/projects
    devices:
      - /dev/ttyUSB0
    stdin_open: true
    tty: true
    restart: 'no'
    working_dir: /projects
